/*
 * openapi server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// OkaserverAPIService is a service that implements the logic for the OkaserverAPIServicer
// This service should implement the business logic for every endpoint for the OkaserverAPI API.
// Include any external packages or services that will be required by this service.
type OkaserverAPIService struct {
}

// NewOkaserverAPIService creates a default api service
func NewOkaserverAPIService() OkaserverAPIServicer {
	return &OkaserverAPIService{}
}

// Getokainfo - get oka info
func (s *OkaserverAPIService) Getokainfo(ctx context.Context) (ImplResponse, error) {
	// TODO - update Getokainfo with the required logic for this service method.
	// Add api_okaserver_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Okaserver{}) or use other options such as http.Ok ...
	// return Response(200, Okaserver{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Getokainfo method not implemented")
}
